# Generated by Django 6.0.5 on 2026-06-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_id_alter_postmedia_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_save', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='post_savedp_user_id_0c2410_idx'), models.Index(fields=['post'], name='post_savedp_post_id_8bfdd0_idx'), models.Index(fields=['created_at'], name='post_savedp_created_ec8424_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_save')],
            },
        ),
    ]
