# Generated by Django 5.2.14 on 2026-05-30 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker'], name='users_block_blocker_473eda_idx'), models.Index(fields=['blocked'], name='users_block_blocked_96f89d_idx'), models.Index(fields=['created_at'], name='users_block_created_e73d33_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block')],
            },
        ),
        migrations.CreateModel(
            name='RestrictUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restricted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='users_restr_user_id_b9261c_idx'), models.Index(fields=['restricted_user'], name='users_restr_restric_97ad36_idx'), models.Index(fields=['created_at'], name='users_restr_created_1e3614_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'restricted_user'), name='unique_restrict_user'), models.CheckConstraint(condition=models.Q(('user', models.F('restricted_user')), _negated=True), name='prevent_self_restriction')],
            },
        ),
    ]
