# Generated by Django 6.0.5 on 2026-05-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_userprofile_id_follow_and_more'),
        ('users', '0002_alter_userprofile_user_blockuser_restrictuser'),
    ]

    operations = [
    ]
