# Generated by Django 5.2.14 on 2026-06-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_blockuser_id_alter_follow_id_and_more'),
        ('users', '0007_create_follow_tables_fix'),
    ]

    operations = [
    ]
